osx_image: xcode7
language: objective-c

install:
 - brew tap leanprover/lean
 - brew update

script:
 - brew install lean

notifications:
  email:
    recipients:
     - soonho.kong@gmail.com
    on_success: change
    on_failure: always
